-- ASPIRANT TEST AI — Supabase database setup
-- Run this entire file once in Supabase -> SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  free_tests_remaining integer not null default 2 check (free_tests_remaining >= 0),
  credits integer not null default 0 check (credits >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.shared_tests (
  id uuid primary key,
  owner_user_id uuid references public.profiles(id) on delete set null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists shared_tests_owner_idx on public.shared_tests(owner_user_id);
create index if not exists shared_tests_expiry_idx on public.shared_tests(expires_at);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  test_id uuid not null references public.shared_tests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score numeric not null,
  percentage numeric not null,
  correct integer not null,
  wrong integer not null,
  unattempted integer not null,
  time_spent_seconds integer not null default 0,
  submitted_at timestamptz not null default now(),
  unique(test_id, user_id)
);
create index if not exists attempts_rank_idx on public.attempts(test_id, score desc, time_spent_seconds asc);

-- Each genuine signed-in student can count only once toward a creator's referral total.
create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  referred_user_id uuid not null references public.profiles(id) on delete cascade,
  first_test_id uuid references public.shared_tests(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(owner_user_id, referred_user_id),
  check (owner_user_id <> referred_user_id)
);
create index if not exists referrals_owner_idx on public.referrals(owner_user_id);

-- Tables are accessed by the server using the service role. Keep direct public table access blocked.
alter table public.profiles enable row level security;
alter table public.shared_tests enable row level security;
alter table public.attempts enable row level security;
alter table public.referrals enable row level security;

-- Consume one generation entitlement atomically.
create or replace function public.consume_generation_allowance(p_user uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.profiles%rowtype;
  source text;
begin
  select * into p from public.profiles where id = p_user for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'profile_missing');
  end if;

  if p.free_tests_remaining > 0 then
    update public.profiles
      set free_tests_remaining = free_tests_remaining - 1
      where id = p_user
      returning * into p;
    source := 'free';
  elsif p.credits > 0 then
    update public.profiles
      set credits = credits - 1
      where id = p_user
      returning * into p;
    source := 'credit';
  else
    return jsonb_build_object(
      'ok', false,
      'reason', 'no_allowance',
      'free_tests_remaining', p.free_tests_remaining,
      'credits', p.credits
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'source', source,
    'free_tests_remaining', p.free_tests_remaining,
    'credits', p.credits
  );
end;
$$;

create or replace function public.refund_generation_allowance(p_user uuid, p_source text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_source = 'free' then
    update public.profiles set free_tests_remaining = free_tests_remaining + 1 where id = p_user;
  elsif p_source = 'credit' then
    update public.profiles set credits = credits + 1 where id = p_user;
  end if;
end;
$$;

-- Save the student's best result, calculate rank, and award one test credit
-- each time a creator reaches another 10 UNIQUE signed-in students.
create or replace function public.record_attempt_and_referral(
  p_test uuid,
  p_user uuid,
  p_owner uuid,
  p_score numeric,
  p_percentage numeric,
  p_correct integer,
  p_wrong integer,
  p_unattempted integer,
  p_time_spent integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_referral boolean := false;
  referral_total integer := 0;
  credit_awarded boolean := false;
  current_score numeric;
  current_time integer;
  rank_no integer;
  participant_total integer;
begin
  insert into public.attempts(test_id,user_id,score,percentage,correct,wrong,unattempted,time_spent_seconds)
  values(p_test,p_user,p_score,p_percentage,p_correct,p_wrong,p_unattempted,greatest(0,p_time_spent))
  on conflict(test_id,user_id) do update
    set score = excluded.score,
        percentage = excluded.percentage,
        correct = excluded.correct,
        wrong = excluded.wrong,
        unattempted = excluded.unattempted,
        time_spent_seconds = excluded.time_spent_seconds,
        submitted_at = now()
    where excluded.score > public.attempts.score
       or (excluded.score = public.attempts.score and excluded.time_spent_seconds < public.attempts.time_spent_seconds);

  if p_owner is not null and p_owner <> p_user then
    insert into public.referrals(owner_user_id,referred_user_id,first_test_id)
    values(p_owner,p_user,p_test)
    on conflict(owner_user_id,referred_user_id) do nothing;
    inserted_referral := found;

    select count(*) into referral_total from public.referrals where owner_user_id = p_owner;
    if inserted_referral and referral_total > 0 and mod(referral_total,10) = 0 then
      update public.profiles set credits = credits + 1 where id = p_owner;
      credit_awarded := true;
    end if;
  end if;

  select score,time_spent_seconds into current_score,current_time
    from public.attempts where test_id=p_test and user_id=p_user;

  select 1 + count(*) into rank_no
    from public.attempts
    where test_id=p_test
      and (score > current_score or (score = current_score and time_spent_seconds < current_time));

  select count(*) into participant_total from public.attempts where test_id=p_test;

  return jsonb_build_object(
    'rank', rank_no,
    'participants', participant_total,
    'referral_counted', inserted_referral,
    'referral_total', referral_total,
    'credit_awarded_to_creator', credit_awarded
  );
end;
$$;
